// cli/templates/angular/reasoning-steps.component.ts
import { Component, input, signal } from "@angular/core"
import type { ReasoningStep } from "llm-chat-ui"

@Component({
  selector: "reasoning-steps",
  standalone: true,
  template: `
    @if (steps().length > 0) {
      <div class="reasoning-steps">
        <button class="toggle-btn" (click)="showAll.set(!showAll())">
          <span class="chevron" [class.collapsed]="!showAll()">v</span>
          {{ showAll() ? 'Hide steps' : 'Show steps' }}
        </button>
        @if (showAll()) {
          <div>
            @for (step of steps(); track step.id) {
              <div class="step-row">
                <div class="step-icon">
                  @if (step.type === 'thinking') {
                    <div class="dot"></div>
                  } @else {
                    @if (step.status === 'running') {
                      <div class="spinner"></div>
                    } @else {
                      <span class="tool-icon">T</span>
                    }
                  }
                </div>
                <button class="step-content" [class.clickable]="!!step.content" (click)="step.content ? toggleStep(step.id) : null">
                  <span class="step-title">{{ step.title }}</span>
                  @if (step.type === 'tool' && step.resultCount && step.resultCount > 0 && step.status === 'success') {
                    <span class="result-count">{{ step.resultCount }} results</span>
                  }
                  <span class="expand-icon" [class.rotated]="expandedSteps().has(step.id)" [class.invisible]="!step.content">v</span>
                </button>
                @if (expandedSteps().has(step.id) && step.content) {
                  <div class="step-detail">
                    @for (line of step.content.split('\\n'); track $index) {
                      @if (line.trim()) {
                        <div class="detail-line">{{ line }}</div>
                      }
                    }
                  </div>
                }
              </div>
            }
          </div>
        }
      </div>
    }
  `,
  styles: [`
    .reasoning-steps { margin-bottom: 8px; }
    .toggle-btn { display: flex; align-items: center; gap: 8px; font-size: 14px; color: #888; cursor: pointer; background: none; border: none; margin-bottom: 8px; padding: 0; }
    .chevron { transition: transform 0.2s; display: inline-block; font-size: 12px; }
    .chevron.collapsed { transform: rotate(-90deg); }
    .step-row { position: relative; display: flex; flex-wrap: wrap; align-items: flex-start; }
    .step-icon { width: 16px; height: 32px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    .dot { width: 6px; height: 6px; border-radius: 50%; background: #888; }
    .spinner { width: 14px; height: 14px; border: 2px solid #e5e5e5; border-top-color: #888; border-radius: 50%; animation: spin 0.8s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }
    .tool-icon { font-size: 12px; color: #888; }
    .step-content { display: flex; align-items: center; gap: 8px; height: 32px; flex: 1; background: none; border: none; text-align: left; min-width: 0; padding: 0 0 0 8px; }
    .step-content.clickable { cursor: pointer; }
    .step-title { flex: 1; font-size: 14px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .result-count { font-size: 12px; color: rgba(128,128,128,0.5); flex-shrink: 0; width: 64px; text-align: right; }
    .expand-icon { flex-shrink: 0; font-size: 12px; color: #888; transition: transform 0.2s; display: inline-block; }
    .expand-icon.rotated { transform: rotate(180deg); }
    .expand-icon.invisible { visibility: hidden; }
    .step-detail { width: 100%; margin: 4px 0 4px 24px; max-height: 192px; overflow-y: auto; }
    .detail-line { font-size: 11px; color: rgba(128,128,128,0.7); font-family: monospace; overflow-wrap: break-word; }
  `],
})
export class ReasoningStepsComponent {
  steps = input.required<ReasoningStep[]>()
  showAll = signal(true)
  expandedSteps = signal(new Set<string>())

  toggleStep(id: string) {
    const next = new Set(this.expandedSteps())
    if (next.has(id)) next.delete(id)
    else next.add(id)
    this.expandedSteps.set(next)
  }
}

// cli/templates/reasoning-steps.tsx
import { useEffect, useRef, useState } from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { ChevronDown, Wrench, type LucideIcon } from "lucide-react"
import { clsx } from "clsx"
import type { ReasoningStep } from "llm-chat-ui"

const TOOL_ICONS: Record<string, LucideIcon> = {}

function getToolIcon(step: ReasoningStep): LucideIcon {
  if (step.icon && TOOL_ICONS[step.icon]) return TOOL_ICONS[step.icon]
  if (step.toolName && TOOL_ICONS[step.toolName]) return TOOL_ICONS[step.toolName]
  return Wrench
}

function ThinkingStep({
  step,
  expanded,
  onToggle,
  isNew,
}: {
  step: ReasoningStep
  expanded: boolean
  onToggle: () => void
  isNew: boolean
}) {
  const ref = useRef<HTMLDivElement>(null)
  const hasContent = !!step.content
  const isRunning = step.status === "running"

  useEffect(() => {
    if (isNew && ref.current) {
      ref.current.style.opacity = "0"
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (ref.current) {
            ref.current.style.transition = "opacity 0.4s ease-out"
            ref.current.style.opacity = "1"
          }
        })
      })
    }
  }, [isNew])

  return (
    <div ref={ref} className="relative" style={{ opacity: isNew ? 0 : 1 }}>
      <div className="flex items-center gap-2 h-8">
        <div className="size-4 flex items-center justify-center shrink-0 relative z-10">
          <div className="size-1.5 rounded-full bg-muted-foreground" />
        </div>
        {hasContent ? (
          <button
            onClick={onToggle}
            className="flex-1 flex items-center justify-between text-left cursor-pointer min-w-0"
          >
            <span className={clsx("text-sm text-muted-foreground truncate", isRunning && "animate-breathe")}>
              {step.title}
            </span>
            <ChevronDown
              className={clsx(
                "size-4 text-muted-foreground transition-transform shrink-0",
                expanded && "rotate-180",
              )}
            />
          </button>
        ) : (
          <span className={clsx("flex-1 text-sm text-muted-foreground truncate", isRunning && "animate-breathe")}>
            {step.title}
          </span>
        )}
      </div>
      {expanded && hasContent && (
        <div className="mt-1 ml-6 max-h-48 overflow-y-auto mb-1">
          <div className="prose prose-sm dark:prose-invert max-w-none text-muted-foreground/70 break-words">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {step.content!}
            </ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  )
}

function ToolStep({
  step,
  expanded,
  onToggle,
  isNew,
}: {
  step: ReasoningStep
  expanded: boolean
  onToggle: () => void
  isNew: boolean
}) {
  const ref = useRef<HTMLDivElement>(null)
  const isRunning = step.status === "running"
  const Icon = getToolIcon(step)
  const hasContent = !!step.content

  useEffect(() => {
    if (isNew && ref.current) {
      ref.current.style.opacity = "0"
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (ref.current) {
            ref.current.style.transition = "opacity 0.4s ease-out"
            ref.current.style.opacity = "1"
          }
        })
      })
    }
  }, [isNew])

  return (
    <div ref={ref} className="relative" style={{ opacity: isNew ? 0 : 1 }}>
      <div className="flex items-center gap-2 h-8">
        <div className="size-4 flex items-center justify-center shrink-0 relative z-10">
          <div className="absolute size-3 bg-background" />
          <Icon className="size-3.5 text-muted-foreground relative" />
        </div>
        <button
          onClick={hasContent ? onToggle : undefined}
          className={clsx(
            "flex-1 flex items-center gap-2 text-left min-w-0",
            hasContent && "cursor-pointer",
          )}
        >
          <span className={clsx("flex-1 text-sm truncate", isRunning && "animate-breathe")}>{step.title}</span>
          <span className="text-xs text-muted-foreground/50 shrink-0 w-16 text-right">
            {step.resultCount !== undefined && step.resultCount > 0 && step.status === "success"
              ? `${step.resultCount} results`
              : ""}
          </span>
          <ChevronDown
            className={clsx(
              "size-4 text-muted-foreground transition-transform shrink-0",
              expanded && "rotate-180",
              !hasContent && "invisible",
            )}
          />
        </button>
      </div>
      {expanded && hasContent && (
        <div className="mt-1 ml-6 max-h-48 overflow-y-auto mb-1 space-y-0.5">
          {step
            .content!.split("\n")
            .filter(Boolean)
            .map((line, i) => (
              <div
                key={i}
                className="text-[11px] text-muted-foreground/70 font-mono break-words"
              >
                {line}
              </div>
            ))}
        </div>
      )}
    </div>
  )
}

interface ReasoningStepsProps {
  steps: ReasoningStep[]
}

export function ReasoningSteps({ steps }: ReasoningStepsProps) {
  const [showAll, setShowAll] = useState(true)
  const [expandedSteps, setExpandedSteps] = useState<Set<string>>(new Set())
  const seenRef = useRef<Set<string>>(new Set())
  const [newSteps, setNewSteps] = useState<Set<string>>(new Set())
  const containerRef = useRef<HTMLDivElement>(null)
  const [lineHeight, setLineHeight] = useState(0)

  useEffect(() => {
    const newIds = new Set<string>()
    steps.forEach((s) => {
      if (!seenRef.current.has(s.id)) {
        newIds.add(s.id)
        seenRef.current.add(s.id)
      }
    })
    if (newIds.size > 0) {
      requestAnimationFrame(() => setNewSteps(newIds))
      const timer = setTimeout(() => setNewSteps(new Set()), 500)
      return () => clearTimeout(timer)
    }
  }, [steps])

  useEffect(() => {
    const update = () => {
      if (!containerRef.current || steps.length < 2) {
        setLineHeight(0)
        return
      }
      const children = containerRef.current.children
      if (children.length < 2) return
      const first = children[0] as HTMLElement
      const last = children[children.length - 1] as HTMLElement
      setLineHeight(last.offsetTop - first.offsetTop)
    }
    update()
    const timer = setTimeout(update, 50)
    return () => clearTimeout(timer)
  }, [steps, expandedSteps, showAll])

  if (steps.length === 0) return null

  const toggleStep = (id: string) => {
    setExpandedSteps((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  return (
    <div className="mb-2">
      <button
        onClick={() => setShowAll((v) => !v)}
        className="flex items-center gap-2 text-sm text-muted-foreground cursor-pointer mb-2"
      >
        {showAll ? (
          <ChevronDown className="size-4" />
        ) : (
          <ChevronDown className="size-4 -rotate-90" />
        )}
        {showAll ? "Hide steps" : "Show steps"}
      </button>
      {showAll && (
        <div className="relative">
          {steps.length > 1 && lineHeight > 0 && (
            <div
              className="absolute left-2 w-px bg-muted-foreground/30 -translate-x-1/2"
              style={{ top: 16, height: lineHeight }}
            />
          )}
          <div ref={containerRef}>
            {steps.map((step) =>
              step.type === "thinking" ? (
                <ThinkingStep
                  key={step.id}
                  step={step}
                  expanded={expandedSteps.has(step.id)}
                  onToggle={() => toggleStep(step.id)}
                  isNew={newSteps.has(step.id)}
                />
              ) : (
                <ToolStep
                  key={step.id}
                  step={step}
                  expanded={expandedSteps.has(step.id)}
                  onToggle={() => toggleStep(step.id)}
                  isNew={newSteps.has(step.id)}
                />
              ),
            )}
          </div>
        </div>
      )}
    </div>
  )
}
